### ISSUE TITLE
Console output doubled up

### ISSUE THREAD

**Issue by swichers** [jelmer/silver-platter#131]
svp 0.5.7

Attempting to run a command results in doubled up output. Example:

```
~/d/app-example ❯❯❯ /home/user/.local/bin/svp run --recipe=./dbg.yml -- git@github.com:user/app-example.git
Branch dbg already exists (branch at git+ssh://git@github.com/user/app-example.git,branch=dbg)
Total 1624 (delta 1), reused 4 (delta 0), pack-reused 1611
Total 1624 (delta 1), reused 4 (delta 0), pack-reused 1611
Committing to: /tmp/tmponup_b4c/
Committing to: /tmp/tmponup_b4c/
added dbg.txt
added dbg.txt
Committed revision 131.
Committed revision 131.
Text conflict in
Text conflict in
Reusing existing repository https://github.com/user/app-example
Reusing existing repository https://github.com/user/app-example
found 0 deltas to reuse
found 0 deltas to reuse
<snip unrelated err>
```

Using something like `--version` or `--help` does not double the output

```
~/d/app-example ❯❯❯ /home/user/.local/bin/svp --version
svp 0.5.7
```

```
 ~/d/app-example ❯❯❯ /home/user/.local/bin/svp --help apply
usage: svp [-h] [--diff] [--commit-pending {yes,no,auto}] [--verify-command VERIFY_COMMAND] [--recipe RECIPE] [command]
<snip>
```

In case it is relevant, this is the recipe I am testing with

```yml
---
name: dbg
command: |-
  echo test recipes
  echo
  echo 'create new file' > dbg.txt
mode: propose
merge-request:
  commit-message: Testing silver platter recipes
```
